<a href="https://colab.research.google.com/github/TK-Problem/Python-mokymai/blob/master/Scripts/linkedin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#@title Importuoti paketus

# duomenų atsisiuntimui per API
import requests

# reikalinga atsiųstą tekstą paversti į json/dict
import json

# paketai dirbti su skaičiais ir duomenimis
import pandas as pd
import numpy as np

Norint atsisųsti LinkedIn darbo pasiųlymų duomenis, reikia:

* užsiregistruoti rapid api svetainėje https://rapidapi.com/.
* užsisakyti nemokamą planą https://rapidapi.com/letscrape-6bRBa3QguO5/api/jsearch/ . Leidžia nemokamai per mėnesį atlikti 50 paieškas.
* išsisaugoti savo API raktą, jo reikės atliekant užklausas.

In [2]:
#@title Atsisiųsti duomenis
# paieškos žodis
SEARCH = 'python vilnius' # @param {type:"string"}
# pasiimti iš RapidAPI
API = '' # @param {type:"string"}
# kiek puslapių ieškoti
# Note: requests for more than one page and up to 10 pages are charged x2 and 
# requests for more than 10 pages are charged 3x.
NUM_PAGES = '10' # @param {type:"string"}

# API url
url = "https://jsearch.p.rapidapi.com/search"

# generate query string
querystring = {"query": SEARCH,"num_pages": NUM_PAGES}

# create header for 
headers = {
	"X-RapidAPI-Key": API,
	"X-RapidAPI-Host": "jsearch.p.rapidapi.com"
}

# get response
response = requests.request("GET", url, headers=headers, params=querystring)

In [3]:
#@title Suformatuoti duomenis
# convert to json
output = json.loads(response.text)

# convert to pandas DataFrame
df = pd.DataFrame(output['data'])

# print message
print(f'Pagal paiešką "{SEARCH}" buvo rasti {len(df)} darbo skelbimai.')

# send message
df.head()

Pagal paiešką "python vilnius" buvo rasti 39 darbo skelbimai.

,employer_name,employer_logo,employer_website,job_publisher,job_id,job_employment_type,job_title,job_apply_link,job_description,job_is_remote,...,job_offer_expiration_timestamp,job_required_experience,job_required_skills,job_required_education,job_experience_in_place_of_education,job_min_salary,job_max_salary,job_salary_currency,job_salary_period,job_highlights
0,BALTO trader,https://encrypted-tbn0.gstatic.com/images?q=tb...,None,LinkedIn,Q8VNnUCNI4YAAAAAAAAAAA==,FULLTIME,Python (Mid/Senior) Full-Stack Developer,https://lt.linkedin.com/jobs/view/python-mid-s...,BALTO trader manages 4 projects: the largest o...,False,...,1.674724e+09,"{'no_experience_required': False, 'required_ex...",None,"{'postgraduate_degree': False, 'professional_c...",False,None,None,None,None,{}
1,Canonical,https://assets.ubuntu.com/v1/7de55930-canonica...,http://www.canonical.com,LinkedIn,2wXy08HdVyQAAAAAAAAAAA==,FULLTIME,"Python Software Engineer, Commercial Systems",https://lt.linkedin.com/jobs/view/python-softw...,This engineering role is an opportunity for a ...,True,...,1.674233e+09,"{'no_experience_required': False, 'required_ex...",None,"{'postgraduate_degree': False, 'professional_c...",False,None,None,None,None,{}
2,CyberCare,None,None,CVbankas.lt,TQyzfQZi2F4AAAAAAAAAAA==,None,Python Developer,https://www.cvbankas.lt/python-developer-vilni...,We believe in a world where the internet is wi...,False,...,1.673309e+09,"{'no_experience_required': False, 'required_ex...",None,"{'postgraduate_degree': False, 'professional_c...",False,None,None,None,None,{}
3,iTechArt,https://encrypted-tbn0.gstatic.com/images?q=tb...,http://www.itechart.com,ITechArt,rnG1RXZSSfcAAAAAAAAAAA==,FULLTIME,Middle Python Developer,https://join.itechart.com/job-openings/middle-...,We’re looking for a Middle Python Engineer to ...,False,...,NaN,"{'no_experience_required': False, 'required_ex...",None,"{'postgraduate_degree': False, 'professional_c...",False,None,None,None,None,{}
4,Canonical,https://assets.ubuntu.com/v1/7de55930-canonica...,http://www.canonical.com,LinkedIn,oAMsdn-9Tu4AAAAAAAAAAA==,FULLTIME,Senior Software Engineer - Identity Management...,https://lt.linkedin.com/jobs/view/senior-softw...,Canonical is seeking experienced Python/Go dev...,True,...,1.674319e+09,"{'no_experience_required': False, 'required_ex...",None,"{'postgraduate_degree': False, 'professional_c...",False,None,None,None,None,{}

# Išsaugoti duomenis

Atkomentuoti eilutes su `CTR + /` ir išsaugoti norimu formatu.

Norint atsisiųsti duomenis lokaliai paspauskite ant dešinėje pusė esančios "Files" ikonos ir atsisiųskite norimą failą. Jei to nepadarysite, failai bus ištrinti uždarius google colab.

![image info](https://i.stack.imgur.com/mYWnb.png)

In [3]:
# excel
# df_c.to_excel(f"darbai.xlsx", index = False)
# .csv
# df_c.to_csv(f"darbai.csv", index = False)